### ISSUE TITLE
rams-jaxrs-cli unable to generate all the pojo with multiple raml files

### ISSUE THREAD

**Issue by joezhou888** [mulesoft-labs/raml-for-jax-rs#333] opened 2018-02-20 23:37 UTC
[Course Application Service.zip](https://github.com/mulesoft-labs/raml-for-jax-rs/files/1742316/Course.Application.Service.zip)

./target/raml-to-jaxrs-cli-2.1.1-SNAPSHOT-jar-with-dependencies.jar -d /Users/joe/project/workspace/admission2/src/main/java/  -r  edu.sydney.ict.admission.rest.pojo ~/project/software/Course\ Application\ Service/courseapplicationservice.raml 

The process works fine. No error.

The issue is that it is not picking up all raml files that are included more then 1 depth.

**Comment by jpbelang** [comment] 2018-02-21 11:49
I'm not understanding what the issue is:  you are specifying a RAML file:  it's going to pick up that specific RAML file.  Are you talking about includes ?

PS:  you seem to be using maven (from the paths).  Is there a reason you are not using the maven plugin ?

**Comment by joezhou888** [comment] 2018-02-21 23:02
Yes I am talking about the includes. It is not picking up includes that is inside another includes.

I will give maven plugin ago.  It is just cli looks easy to use.

**Comment by jpbelang** [comment] 2018-02-21 23:03
Can you give me a snippet ? Like The top file and an include ?

**Comment by joezhou888** [comment] 2018-02-22 04:33
In the attached Course Application Service.zip above.
courseapplicationservice.raml has includes that references to !include schemas.json/response/ApplicationResponse.raml then ApplicationResponse.raml has includes to !include ../admissionTestResult/AdmissionTestResult.raml

It is not generating the pojo for AdmissionTestResult.raml

**Comment by jpbelang** [comment] 2018-02-22 13:35
I'm at work, I'll check tonight for sure.

**Comment by jpbelang** [comment] 2018-02-22 21:14
Things need to be attached to the "topmost" raml file:  the processor starts from the topmost and finds types through this.  They need to be declared as types in the raml file.  

For example
types: 
  KeyRequest : !include schemas.json/request/KeyRequest.raml
  KeyResponse : !include schemas.json/response/KeyResponse.raml
  ApplicationRequest: !include schemas.json/request/ApplicationRequest.raml
  ApplicationResponse: !include schemas.json/response/ApplicationResponse.raml
  AdmissionTestResult: !include schemas.json/admissionTestResult/AdmissionTestResult.raml
  
A good starting point would be here:
https://github.com/spotify/ramlfications/wiki/RAML-v1.0:-Data-Types

For the record, I think it would be better to use the raml "uses" to fetch libraries that define new types.

**Comment by joezhou888** [comment] 2018-02-25 21:51
Thanks you for explaining.
This really helps, I will give it ago.

**Comment by jpbelang** [comment] 2018-02-25 23:27
I'll close the issue.  Should you have another question, don't be shy about coming back here.

**Closed by jpbelang** 2018-02-25 23:27 UTC
