### ISSUE TITLE
Schema reference $ref with subdir fails with "Unrecognised URI"

### ISSUE THREAD

**Issue by julianladisch** [mulesoft-labs/raml-for-jax-rs#362] opened 2018-09-07 21:11 UTC
I have this directory layout:
```
+- subdir.raml
+- subdir1.json
+- subdir
   +- subdir2.json
```
subdir.raml successfully references subdir1.json.
subdir1.json contains this schema reference: `"$ref": "subdir/subdir2.json"`
It fails with this error message:
`[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.2-SNAPSHOT:generate (default) on project references2: Error generating Java classes from: null: Unrecognised URI, can't resolve this: file:/tmp/1536354404635-0/subdir/subdir2.json: /tmp/1536354404635-0/subdir/subdir2.json (No such file or directory) -> [Help 1]`
I've uploaded a complete example at https://github.com/julianladisch/raml-for-jax-rs/tree/subdir/raml-to-jaxrs/examples/maven-examples/references2

**Comment by jpbelang** [comment] 2018-09-09 23:32
I'll look at this this week.

**Comment by deadline98** [comment] 2019-02-04 14:40
+1 we just encountered the same issue (we migrated to mono-repo and therefore it's crucial to have relative import)

**Comment by cpkr** [comment] 2019-02-05 15:45
@jpbelang: Root cause is that the json is placed into the raml structure as is without resolving the path in the references. I temporarily fixed it for our code generation process using following steps:
- Changed version of raml-parser-2  in raml-for-jaxrs to 1.0.31-SNAPSHOT
- Update includeContent in IncludeResolve before creation of StringNodeImpl:
```
                File file = new File(resourcePath);
                String replacementParentDir = file.getParentFile().getParent() + "/";
                String replacementSameDir = file.getParent() + "/";
                includeContent = includeContent.replaceAll("\"\\$ref\": \"\\.\\./", "\"\\$ref\": \"" + replacementParentDir);
                includeContent = includeContent.replaceAll("\"\\$ref\": \"\\./", "\"\\$ref\": \"" + replacementSameDir);

```

Afterwards the referenced path is always an absolute path.

**Comment by jpbelang** [comment] 2019-02-17 19:53
@cpkr  The fix works for you, but it wouldn't work in all circumstances ( regexp are notably finicky, and changing the parser probably wouldn't be the right solution).  One of the reasons for this is that the parser is slowly going away.  

@deadline98 I was wondering if you could change the reference to what the reference example ?  Adding the java: prefix so the it would use the classpath instead of relative paths ?  

Otherwise, I'm still looking.

**Comment by jpbelang** [comment] 2019-02-17 22:27
Ok, I've tried something.  I hope I haven't messed up :-)

I've added this:
https://github.com/mulesoft-labs/raml-for-jax-rs/blob/dded9d0597daeeeac4565afbe7de43eddb8bbe69/raml-to-jaxrs/examples/maven-examples/references/pom.xml#L84

I think this is a better fix than originally.  We'll see. But right now, the flag is required.

**Comment by cpkr** [comment] 2019-02-18 08:10
@jpbelang The fix does not work for us. I added the copySchemas attribute and gave it a try. Still getting 

[ERROR] Failed to execute goal org.raml.jaxrs:raml-to-jaxrs-maven-plugin:3.0.4-SNAPSHOT:generate (secure) on project services-restapi-lh: Error generating Java classes from: null: Unrecognised URI, can't resolve this: file:/tmp/CountryEnhanced.json: /tmp/CountryEnhanced.json (No such file or directory) -> [Help 1]

Using the java: prefix is no option for us unfortunately as we do use the same schemas in nodejs. :-(

**Comment by jpbelang** [comment] 2019-02-18 13:15
You are using the wrong version: we are up to 3.0.5-SNAPSHOT.

**Comment by jpbelang** [comment] 2019-02-24 15:27
@cpkr Can you give me an idea of your layout ?  I'll explain what I'm trying to do.

If you have a jsonschema bit into a raml, I need to copy it somewhere where the jsonschematopojo library will be able to handle it.  But if this schema includes something, it will be relative to the  to this new temporary directory.

The flag I added there copies stuff from the raml directory to the temporary directory, so that I have the same file structure and that relative paths should work. 

So, the question becomes, I guess, why didn't it copy the CountryEnhanced.json file ?

**Comment by cpkr** [comment] 2019-02-25 10:16
@jpbelang I will try to strip down our code to have a good example

**Closed** 2019-03-21 02:08 UTC
